DIAG(archive_magic_mismatch,
     DiagnosticEngine::Error,
     "magic number is mismatched in `%0'",
     "magic number is mismatched in `%0'")
DIAG(debug_cannot_parse_eh,
     DiagnosticEngine::Debug,
     "cannot parse .eh_frame section in input %0",
     "cannot parse .eh_frame section in input %0.")
DIAG(debug_cannot_scan_eh,
     DiagnosticEngine::Debug,
     "cannot scan .eh_frame section in input %0",
     "cannot scan .eh_frame section in input %0.")
DIAG(fatal_cannot_read_input,
     DiagnosticEngine::Fatal,
     "cannot read input %0",
     "cannot read input %0")
