void glBlendBarrier ( void )
void glCopyImageSubData ( GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth )
void glDebugMessageControl ( GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled )
void glDebugMessageInsert ( GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf )
void glDebugMessageCallback ( GLDEBUGPROC callback, const void *userParam )
GLuint glGetDebugMessageLog ( GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog )
void glPushDebugGroup ( GLenum source, GLuint id, GLsizei length, const GLchar *message )
void glPopDebugGroup ( void )
void glObjectLabel ( GLenum identifier, GLuint name, GLsizei length, const GLchar *label )
void glGetObjectLabel ( GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label )
void glObjectPtrLabel ( const void *ptr, GLsizei length, const GLchar *label )
void glGetObjectPtrLabel ( const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label )
void glGetPointerv ( GLenum pname, void **params )
void glEnablei ( GLenum target, GLuint index )
void glDisablei ( GLenum target, GLuint index )
void glBlendEquationi ( GLuint buf, GLenum mode )
void glBlendEquationSeparatei ( GLuint buf, GLenum modeRGB, GLenum modeAlpha )
void glBlendFunci ( GLuint buf, GLenum src, GLenum dst )
void glBlendFuncSeparatei ( GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha )
void glColorMaski ( GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a )
GLboolean glIsEnabledi ( GLenum target, GLuint index )
void glDrawElementsBaseVertex ( GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex )
void glDrawRangeElementsBaseVertex ( GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex )
void glDrawElementsInstancedBaseVertex ( GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex )
void glFramebufferTexture ( GLenum target, GLenum attachment, GLuint texture, GLint level )
void glPrimitiveBoundingBox ( GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW )
GLenum glGetGraphicsResetStatus ( void )
void glReadnPixels ( GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data )
void glGetnUniformfv ( GLuint program, GLint location, GLsizei bufSize, GLfloat *params )
void glGetnUniformiv ( GLuint program, GLint location, GLsizei bufSize, GLint *params )
void glGetnUniformuiv ( GLuint program, GLint location, GLsizei bufSize, GLuint *params )
void glMinSampleShading ( GLfloat value )
void glPatchParameteri ( GLenum pname, GLint value )
void glTexParameterIiv ( GLenum target, GLenum pname, const GLint *params )
void glTexParameterIuiv ( GLenum target, GLenum pname, const GLuint *params )
void glGetTexParameterIiv ( GLenum target, GLenum pname, GLint *params )
void glGetTexParameterIuiv ( GLenum target, GLenum pname, GLuint *params )
void glSamplerParameterIiv ( GLuint sampler, GLenum pname, const GLint *param )
void glSamplerParameterIuiv ( GLuint sampler, GLenum pname, const GLuint *param )
void glGetSamplerParameterIiv ( GLuint sampler, GLenum pname, GLint *params )
void glGetSamplerParameterIuiv ( GLuint sampler, GLenum pname, GLuint *params )
void glTexBuffer ( GLenum target, GLenum internalformat, GLuint buffer )
void glTexBufferRange ( GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size )
void glTexStorage3DMultisample ( GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations )
